# Generated by Django 5.0.6 on 2024-06-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_id',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
