# Generated by Django 5.0.6 on 2024-06-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_id',
        ),
    ]
