# Generated by Django 5.0.6 on 2024-06-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('ES', 'Spanish')], default='EN', max_length=2),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
