import App from './App.js';
import LanguageProvider from './components/LanguageProvider.js';
import BaseButton from './components/BaseButton.js';
import ModesButton from "./components/ModesButton.js";
import CloseButton from './components/CloseButton.js';
import BackButton from './components/BackButton.js';
import Login from './pages/Login.js';
import TwoFactorAuth from './pages/2FA.js';
import MainMenu from './pages/MainMenu.js';
import TournamentHistory from './pages/TournamentHistory.js';
import Winner from './pages/Winner.js';
import Loser from './pages/Loser.js';
import PopUpModes from './pages/PopUpModes.js';
import PopUpTournament from './pages/PopUpTournament.js';
import PopUpConfirmation from './components/PopUpConfirmation.js';
import PopUpSettings from './pages/PopUpSettings.js';
import PongLogo from './components/PongLogo.js';
import ProtectedRoute from './components/ProtectedRoute.js';
import PongGamePage from './pages/PongGamePage.js';
import PongAIGamePage from './pages/PongAIGamePage.js';
import PlayerInfo from './components/PlayerInfo.js';
import PongGameBoard from './components/PongGameboard.js';
import PongAIGameBoard from './components/PongAIGameBoard.js';

window.App = App;
window.LanguageProvider = LanguageProvider;
window.BaseButton = BaseButton;
window.ModesButton = ModesButton;
window.CloseButton = CloseButton;
window.BackButton = BackButton;
window.Login = Login;
window.TwoFactorAuth = TwoFactorAuth;
window.MainMenu = MainMenu;
window.TournamentHistory = TournamentHistory;
window.Winner = Winner;
window.Loser = Loser;
window.PopUpModes = PopUpModes;
window.PopUpTournament = PopUpTournament;
window.PopUpConfirmation = PopUpConfirmation;
window.PopUpSettings = PopUpSettings;
window.PongLogo = PongLogo;
window.ProtectedRoute = ProtectedRoute;
window.PongGamePage = PongGamePage;
window.PongAIGamePage = PongAIGamePage;
window.PlayerInfo = PlayerInfo;
window.PongGameBoard = PongGameBoard;
window.PongAIGameBoard = PongAIGameBoard;