import BaseButton from './components/BaseButton.js';
import ModesButton from "./components/ModesButton.js";
import CloseButton from './components/CloseButton.js';
import Login from './pages/Login.js';
import TwoFactorAuth from './pages/2FA.js';
import MainMenu from './pages/MainMenu.js';
import Winner from './pages/Winner.js';
//import Loser from './pages/Loser.js';
import PopUpModes from './pages/PopUpModes.js';
import PopUpTournament from './pages/PopUpTournament.js';
import App from './App.js';
import PongLogo from './components/PongLogo.js';

window.App = App;
window.BaseButton = BaseButton;
window.ModesButton = ModesButton;
window.CloseButton = CloseButton;
window.Login = Login;
window.TwoFactorAuth = TwoFactorAuth;
window.MainMenu = MainMenu;
window.Winner = Winner;
//window.Loser = Loser;
window.PopUpModes = PopUpModes;
window.PopUpTournament = PopUpTournament;
window.PongLogo = PongLogo;